//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sweepnet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sweepnet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;&lt;style&gt;table.diff, td.diff-otitle, td.diff-ntitle {background-color:#333;color:#fff;}td.diff-otitle,td.diff-ntitle {text-align: center;}td.diff-marker {text-align:right;font-size:18px;font-weight:bold;padding:3px;text-align:center;}.rtl td.diff-marker {text-align: left;}table.diff td.diff-lineno {padding-left:15px;font-weight: bold;}td.diff-deletedline {background: #ffe0e0;}td.diff-addedline {background-color: rgb(216, 228, 246);color: rgb(0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string diff_head_en_i18n {
            get {
                return ResourceManager.GetString("diff_head_en_i18n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;&lt;style&gt;table.diff, td.diff-otitle, td.diff-ntitle {background-color:#333;color:#fff;}td.diff-otitle,td.diff-ntitle {text-align: center;}td.diff-marker {text-align:right;font-size:18px;font-weight:bold;padding:3px;text-align:center;}.rtl td.diff-marker {text-align: left;}table.diff td.diff-lineno {padding-left:15px;font-weight: bold;}td.diff-deletedline {background: #ffe0e0;}td.diff-addedline {background: #e8ffe8;}table.diff {background:#FEFE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string diff_head_old_en_i18n {
            get {
                return ResourceManager.GetString("diff_head_old_en_i18n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;&lt;style&gt;table.diff, td.diff-otitle, td.diff-ntitle {background-color:#333;color:#fff;}td.diff-otitle,td.diff-ntitle {text-align: center;}td.diff-marker {text-align:right;font-size:18px;font-weight:bold;padding:3px;text-align:center;}.rtl td.diff-marker {text-align: left;}table.diff td.diff-lineno {padding-left:15px;font-weight: bold;}td.diff-deletedline {background: #ffe0e0;}td.diff-addedline {background: #e8ffe8;}table.diff {background:#FEFE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string diff_head_old_ru_i18n {
            get {
                return ResourceManager.GetString("diff_head_old_ru_i18n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;&lt;style&gt;table.diff, td.diff-otitle, td.diff-ntitle {background-color:#333;color:#fff;}td.diff-otitle,td.diff-ntitle {text-align: center;}td.diff-marker {text-align:right;font-size:18px;font-weight:bold;padding:3px;text-align:center;}.rtl td.diff-marker {text-align: left;}table.diff td.diff-lineno {padding-left:15px;font-weight: bold;}td.diff-deletedline {background: #ffe0e0;}td.diff-addedline {background: #e8ffe8;}table.diff {background:#FEFE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string diff_head_old_uk_i18n {
            get {
                return ResourceManager.GetString("diff_head_old_uk_i18n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;&lt;style&gt;table.diff, td.diff-otitle, td.diff-ntitle {background-color:#333;color:#fff;}td.diff-otitle,td.diff-ntitle {text-align: center;}td.diff-marker {text-align:right;font-size:18px;font-weight:bold;padding:3px;text-align:center;}.rtl td.diff-marker {text-align: left;}table.diff td.diff-lineno {padding-left:15px;font-weight: bold;}td.diff-deletedline {background: #ffe0e0;}td.diff-addedline {background-color: rgb(216, 228, 246);color: rgb(0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string diff_head_ru_i18n {
            get {
                return ResourceManager.GetString("diff_head_ru_i18n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;&lt;style&gt;table.diff, td.diff-otitle, td.diff-ntitle {background-color:#333;color:#fff;}td.diff-otitle,td.diff-ntitle {text-align: center;}td.diff-marker {text-align:right;font-size:18px;font-weight:bold;padding:3px;text-align:center;}.rtl td.diff-marker {text-align: left;}table.diff td.diff-lineno {padding-left:15px;font-weight: bold;}td.diff-deletedline {background: #ffe0e0;}td.diff-addedline {background-color: rgb(216, 228, 246);color: rgb(0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string diff_head_uk_i18n {
            get {
                return ResourceManager.GetString("diff_head_uk_i18n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;dictionary&gt;
        ///  &lt;!-- !!! --&gt;
        ///  &lt;entry&gt;
        ///    &lt;name&gt;LANGUAGE_0&lt;/name&gt;
        ///    &lt;value&gt;English language&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt;
        ///    &lt;name&gt;LANGUAGE_1&lt;/name&gt;
        ///    &lt;value&gt;English&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt;
        ///    &lt;name&gt;LANGUAGE_2&lt;/name&gt;
        ///    &lt;value&gt;English language&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///  &lt;entry&gt;
        ///    &lt;name&gt;LANGUAGE_3&lt;/name&gt;
        ///    &lt;value&gt;English&lt;/value&gt;
        ///  &lt;/entry&gt;
        ///
        ///  &lt;entry&gt;
        ///    &lt;name&gt;ROLLBACK_SUMMARY&lt;/name&gt;
        ///    &lt;value&gt;Reverting edits and returning to {0} ([[Proj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_i18n {
            get {
                return ResourceManager.GetString("en_i18n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list_new {
            get {
                object obj = ResourceManager.GetObject("list_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list_rb {
            get {
                object obj = ResourceManager.GetObject("list_rb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list_rw {
            get {
                object obj = ResourceManager.GetObject("list_rw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Only one revision is selected.&lt;/b&gt;&lt;br /&gt;&lt;br /&gt;
        ///
        ///You can review it.&lt;br /&gt;.
        /// </summary>
        internal static string pm_1_en_i18n {
            get {
                return ResourceManager.GetString("pm_1_en_i18n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Выделен только один элемент&lt;/b&gt;&lt;br /&gt;&lt;br /&gt;
        ///
        ///Можете его отпатрулировать.&lt;br /&gt;.
        /// </summary>
        internal static string pm_1_ru_i18n {
            get {
                return ResourceManager.GetString("pm_1_ru_i18n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Виділено лише один елемент.&lt;/b&gt;&lt;br /&gt;&lt;br /&gt;
        ///
        ///Можете його відпатрулювати.&lt;br /&gt;.
        /// </summary>
        internal static string pm_1_uk_i18n {
            get {
                return ResourceManager.GetString("pm_1_uk_i18n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;dictionary&gt;
        ///  &lt;!-- !!! --&gt;
        ///  &lt;entry&gt;&lt;name&gt;LANGUAGE_0&lt;/name&gt;&lt;value&gt;Русский язык&lt;/value&gt;&lt;/entry&gt;
        ///  &lt;entry&gt;&lt;name&gt;LANGUAGE_1&lt;/name&gt;&lt;value&gt;Русский&lt;/value&gt;&lt;/entry&gt;
        ///  &lt;entry&gt;&lt;name&gt;LANGUAGE_2&lt;/name&gt;&lt;value&gt;Russian language&lt;/value&gt;&lt;/entry&gt;
        ///  &lt;entry&gt;&lt;name&gt;LANGUAGE_3&lt;/name&gt;&lt;value&gt;Russian&lt;/value&gt;&lt;/entry&gt;
        ///  
        ///  &lt;entry&gt;&lt;name&gt;ROLLBACK_SUMMARY&lt;/name&gt;&lt;value&gt;Отклонение правок и возврат к версии {0} ([[Project:Sweep-Net|Sweep-Net]])&lt;/value&gt;&lt;/entry&gt;
        ///  &lt;entry&gt;&lt;name&gt;REVIEW_SUMMARY&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ru_i18n {
            get {
                return ResourceManager.GetString("ru_i18n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var elements = document.getElementsByTagName(&apos;td&apos;);
        ///
        ///var stat = new Array(); var tmp;
        ///function onmove(e) {
        ///    var tmp = document.getElementById(&quot;myid&quot;);
        ///    var id = 0;
        ///    var tmp = null;
        ///    if (e.target == null) {
        ///        tmp = e.srcElement;
        ///        id = e.srcElement.getAttribute(&quot;myindex&quot;);
        ///    } else {
        ///        tmp = e.target;
        ///        id = e.target.getAttribute(&quot;myindex&quot;);
        ///    }
        ///
        ///    id = tmp.getAttribute(&quot;myindex&quot;);
        ///
        ///    if (id == null) {
        ///        tmp = tmp.parentElement;
        ///        id  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script {
            get {
                return ResourceManager.GetString("script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;dictionary&gt;
        ///  &lt;!-- !!! --&gt;
        ///  &lt;entry&gt;&lt;name&gt;LANGUAGE_0&lt;/name&gt;&lt;value&gt;Українська мова&lt;/value&gt;&lt;/entry&gt;
        ///  &lt;entry&gt;&lt;name&gt;LANGUAGE_1&lt;/name&gt;&lt;value&gt;Українська&lt;/value&gt;&lt;/entry&gt;
        ///  &lt;entry&gt;&lt;name&gt;LANGUAGE_2&lt;/name&gt;&lt;value&gt;Ukrainian language&lt;/value&gt;&lt;/entry&gt;
        ///  &lt;entry&gt;&lt;name&gt;LANGUAGE_3&lt;/name&gt;&lt;value&gt;Ukrainian&lt;/value&gt;&lt;/entry&gt;
        ///  
        ///  &lt;entry&gt;&lt;name&gt;ROLLBACK_SUMMARY&lt;/name&gt;&lt;value&gt;Відкіт редагувань і повернення до версії {0} ([[Project:Sweep-Net|Sweep-Net]])&lt;/value&gt;&lt;/entry&gt;
        ///  &lt;entry&gt;&lt;name&gt;R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string uk_i18n {
            get {
                return ResourceManager.GetString("uk_i18n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style&gt;
        ///media print{a.stub,a.new{color:#ba0000;text-decoration:none}#toc{border:1px solid #aaaaaa;background-color:#f9f9f9;padding:5px;display:-moz-inline-block;display:inline-block;display:table;zoom:1;*display:inline}div.floatright{float:right;clear:right;position:relative;margin:0.5em 0 0.8em 1.4em}div.floatright p{font-style:italic}div.floatleft{float:left;clear:left;position:relative;margin:0.5em 1.4em 0.8em 0}div.floatleft p{font-style:italic}div.center{text-align:center}div.thumb{border:none;width:a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string view_css_style {
            get {
                return ResourceManager.GetString("view_css_style", resourceCulture);
            }
        }
    }
}
