//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sweepnet.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string i1 {
            get {
                return ((string)(this["i1"]));
            }
            set {
                this["i1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string i2 {
            get {
                return ((string)(this["i2"]));
            }
            set {
                this["i2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string fs {
            get {
                return ((string)(this["fs"]));
            }
            set {
                this["fs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int m {
            get {
                return ((int)(this["m"]));
            }
            set {
                this["m"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string m1 {
            get {
                return ((string)(this["m1"]));
            }
            set {
                this["m1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string m2 {
            get {
                return ((string)(this["m2"]));
            }
            set {
                this["m2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0|6|10|14")]
        public string ns {
            get {
                return ((string)(this["ns"]));
            }
            set {
                this["ns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int diffl {
            get {
                return ((int)(this["diffl"]));
            }
            set {
                this["diffl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool art {
            get {
                return ((bool)(this["art"]));
            }
            set {
                this["art"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool redir {
            get {
                return ((bool)(this["redir"]));
            }
            set {
                this["redir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int final {
            get {
                return ((int)(this["final"]));
            }
            set {
                this["final"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int dir {
            get {
                return ((int)(this["dir"]));
            }
            set {
                this["dir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string options_n {
            get {
                return ((string)(this["options_n"]));
            }
            set {
                this["options_n"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string options_v {
            get {
                return ((string)(this["options_v"]));
            }
            set {
                this["options_v"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string config_n {
            get {
                return ((string)(this["config_n"]));
            }
            set {
                this["config_n"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string config_v {
            get {
                return ((string)(this["config_v"]));
            }
            set {
                this["config_v"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"https://als.wikipedia.org/|https://ar.wikipedia.org/|https://be.wikipedia.org/|https://bs.wikipedia.org/|https://de.wikipedia.org/|https://de.wikiquote.org/|https://eo.wikipedia.org/|https://hu.wikipedia.org/|https://ia.wikipedia.org/|https://id.wikipedia.org/|https://mk.wikipedia.org/|https://pl.wikipedia.org/|https://pl.wikisource.org/|https://ru.wikipedia.org/|https://ru.wikiquote.org/|https://ru.wikisource.org/|https://sq.wikipedia.org/|https://tr.wikipedia.org/|https://uk.wikipedia.org/|https://zh-classical.wikipedia.org/")]
        public string add_url3 {
            get {
                return ((string)(this["add_url3"]));
            }
            set {
                this["add_url3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("als.wiki|ar.wiki|be.wiki|bs.wiki|de.wiki|de.wikiquote|eo.wiki|hu.wiki|ia.wiki|id." +
            "wiki|mk.wiki|pl.wiki|pl.wikisource|ru.wiki|ru.wikiquote|ru.wikisource|sq.wiki|tr" +
            ".wiki|uk.wiki|zh-classical.wiki")]
        public string add_names3 {
            get {
                return ((string)(this["add_names3"]));
            }
            set {
                this["add_names3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-8\" ?>")]
        public string add_customreviewsummaries {
            get {
                return ((string)(this["add_customreviewsummaries"]));
            }
            set {
                this["add_customreviewsummaries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-8\" ?>")]
        public string add_customrollbacksummaries {
            get {
                return ((string)(this["add_customrollbacksummaries"]));
            }
            set {
                this["add_customrollbacksummaries"] = value;
            }
        }
    }
}
